'------------------------------------------------------------------------------
' <auto-generated>
'     Ten kod został wygenerowany przez narzędzie.
'     Wersja wykonawcza:4.0.30319.42000
'
'     Zmiany w tym pliku mogą spowodować nieprawidłowe zachowanie i zostaną utracone, jeśli
'     kod zostanie ponownie wygenerowany.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    'Ta klasa została automatycznie wygenerowana za pomocą klasy StronglyTypedResourceBuilder
    'przez narzędzie, takie jak ResGen lub Visual Studio.
    'Aby dodać lub usunąć składową, edytuj plik ResX, a następnie ponownie uruchom narzędzie ResGen
    'z opcją /str lub ponownie utwórz projekt VS.
    '''<summary>
    '''  Klasa zasobu wymagająca zdefiniowania typu do wyszukiwania zlokalizowanych ciągów itd.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute()>  _
    Friend Class LauncherStrings_pl_PL
        
        Private Shared resourceMan As Global.System.Resources.ResourceManager
        
        Private Shared resourceCulture As Global.System.Globalization.CultureInfo
        
        <Global.System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")>  _
        Friend Sub New()
            MyBase.New
        End Sub
        
        '''<summary>
        '''Zwraca buforowane wystąpienie ResourceManager używane przez tę klasę.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Shared ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("Sims2Launcher.LauncherStrings_pl-PL", GetType(LauncherStrings_pl_PL).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Przesłania właściwość CurrentUICulture bieżącego wątku dla wszystkich
        '''  przypadków przeszukiwania zasobów za pomocą tej klasy zasobów wymagającej zdefiniowania typu.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Shared Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        '''<summary>
        '''Wyszukuje zlokalizowany ciąg podobny do ciągu Pakiety do gry:.
        '''</summary>
        Friend Shared ReadOnly Property Accessories() As String
            Get
                Return ResourceManager.GetString("Accessories", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''Wyszukuje zlokalizowany ciąg podobny do ciągu The Sims™ 2.
        '''</summary>
        Friend Shared ReadOnly Property Base() As String
            Get
                Return ResourceManager.GetString("Base", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''Wyszukuje zlokalizowany ciąg podobny do ciągu The Sims™ 2 Deluxe.
        '''</summary>
        Friend Shared ReadOnly Property Base_D() As String
            Get
                Return ResourceManager.GetString("Base_D", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''Wyszukuje zlokalizowany ciąg podobny do ciągu The Sims™ 2 Double Deluxe.
        '''</summary>
        Friend Shared ReadOnly Property Base_DD() As String
            Get
                Return ResourceManager.GetString("Base_DD", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''Wyszukuje zlokalizowany ciąg podobny do ciągu Anuluj.
        '''</summary>
        Friend Shared ReadOnly Property Cancel() As String
            Get
                Return ResourceManager.GetString("Cancel", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''Wyszukuje zlokalizowany ciąg podobny do ciągu Modyfikacje.
        '''</summary>
        Friend Shared ReadOnly Property CC() As String
            Get
                Return ResourceManager.GetString("CC", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''Wyszukuje zlokalizowany ciąg podobny do ciągu The Sims™ 2 Na studiach.
        '''</summary>
        Friend Shared ReadOnly Property EP1() As String
            Get
                Return ResourceManager.GetString("EP1", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''Wyszukuje zlokalizowany ciąg podobny do ciągu The Sims™ 2 Nocne życie.
        '''</summary>
        Friend Shared ReadOnly Property EP2() As String
            Get
                Return ResourceManager.GetString("EP2", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''Wyszukuje zlokalizowany ciąg podobny do ciągu The Sims™ 2 Własny biznes.
        '''</summary>
        Friend Shared ReadOnly Property EP3() As String
            Get
                Return ResourceManager.GetString("EP3", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''Wyszukuje zlokalizowany ciąg podobny do ciągu The Sims™ 2 Zwierzaki.
        '''</summary>
        Friend Shared ReadOnly Property EP4() As String
            Get
                Return ResourceManager.GetString("EP4", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''Wyszukuje zlokalizowany ciąg podobny do ciągu The Sims™ 2 Cztery pory roku.
        '''</summary>
        Friend Shared ReadOnly Property EP5() As String
            Get
                Return ResourceManager.GetString("EP5", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''Wyszukuje zlokalizowany ciąg podobny do ciągu The Sims™ 2 Podróże.
        '''</summary>
        Friend Shared ReadOnly Property EP6() As String
            Get
                Return ResourceManager.GetString("EP6", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''Wyszukuje zlokalizowany ciąg podobny do ciągu The Sims™ 2 Czas Wolny.
        '''</summary>
        Friend Shared ReadOnly Property EP7() As String
            Get
                Return ResourceManager.GetString("EP7", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''Wyszukuje zlokalizowany ciąg podobny do ciągu The Sims™ 2 Osiedlowe życie.
        '''</summary>
        Friend Shared ReadOnly Property EP8() As String
            Get
                Return ResourceManager.GetString("EP8", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''Wyszukuje zlokalizowany ciąg podobny do ciągu The Sims™ 2 Rezydencje i ogrody Akcesoria.
        '''</summary>
        Friend Shared ReadOnly Property EP9() As String
            Get
                Return ResourceManager.GetString("EP9", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''Wyszukuje zlokalizowany ciąg podobny do ciągu Dodatki do gry:.
        '''</summary>
        Friend Shared ReadOnly Property Expansions() As String
            Get
                Return ResourceManager.GetString("Expansions", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''Wyszukuje zlokalizowany ciąg podobny do ciągu Pełny ekran:.
        '''</summary>
        Friend Shared ReadOnly Property FullScreen() As String
            Get
                Return ResourceManager.GetString("FullScreen", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''Wyszukuje zlokalizowany ciąg podobny do ciągu Język:.
        '''</summary>
        Friend Shared ReadOnly Property Language() As String
            Get
                Return ResourceManager.GetString("Language", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''Wyszukuje zlokalizowany ciąg podobny do ciągu Nie.
        '''</summary>
        Friend Shared ReadOnly Property No() As String
            Get
                Return ResourceManager.GetString("No", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''Wyszukuje zlokalizowany ciąg podobny do ciągu Gra %s nie została zainstalowana lub została zainstalowana nieprawidłowo. Zainstaluj ją po raz pierwszy lub zainstaluj ponownie..
        '''</summary>
        Friend Shared ReadOnly Property NotInstalled() As String
            Get
                Return ResourceManager.GetString("NotInstalled", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''Wyszukuje zlokalizowany ciąg podobny do ciągu Ok.
        '''</summary>
        Friend Shared ReadOnly Property Ok() As String
            Get
                Return ResourceManager.GetString("Ok", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''Wyszukuje zlokalizowany ciąg podobny do ciągu Graj.
        '''</summary>
        Friend Shared ReadOnly Property Play() As String
            Get
                Return ResourceManager.GetString("Play", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''Wyszukuje zlokalizowany ciąg podobny do ciągu Rozdzielczość:.
        '''</summary>
        Friend Shared ReadOnly Property Resolution() As String
            Get
                Return ResourceManager.GetString("Resolution", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''Wyszukuje zlokalizowany ciąg podobny do ciągu Zapisz.
        '''</summary>
        Friend Shared ReadOnly Property Save() As String
            Get
                Return ResourceManager.GetString("Save", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''Wyszukuje zlokalizowany ciąg podobny do ciągu Szukaj.
        '''</summary>
        Friend Shared ReadOnly Property Search() As String
            Get
                Return ResourceManager.GetString("Search", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''Wyszukuje zlokalizowany ciąg podobny do ciągu Ustawienia.
        '''</summary>
        Friend Shared ReadOnly Property Settings() As String
            Get
                Return ResourceManager.GetString("Settings", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''Wyszukuje zlokalizowany ciąg podobny do ciągu The Sims™ 2 Rozrywka rodzinna Akcesoria.
        '''</summary>
        Friend Shared ReadOnly Property SP1() As String
            Get
                Return ResourceManager.GetString("SP1", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''Wyszukuje zlokalizowany ciąg podobny do ciągu The Sims™ 2 Szyk i elegancja Akcesoria.
        '''</summary>
        Friend Shared ReadOnly Property SP2() As String
            Get
                Return ResourceManager.GetString("SP2", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''Wyszukuje zlokalizowany ciąg podobny do ciągu The Sims™ 2 Impreza! Akcesoria.
        '''</summary>
        Friend Shared ReadOnly Property SP4() As String
            Get
                Return ResourceManager.GetString("SP4", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''Wyszukuje zlokalizowany ciąg podobny do ciągu The Sims™ 2 Moda z H&amp;M® Akcesoria.
        '''</summary>
        Friend Shared ReadOnly Property SP5() As String
            Get
                Return ResourceManager.GetString("SP5", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''Wyszukuje zlokalizowany ciąg podobny do ciągu The Sims™ 2 Młodzieżowy styl Akcesoria.
        '''</summary>
        Friend Shared ReadOnly Property SP6() As String
            Get
                Return ResourceManager.GetString("SP6", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''Wyszukuje zlokalizowany ciąg podobny do ciągu The Sims™ 2 Kuchnia i łazienka Wystrój Wnętrz Akcesoria.
        '''</summary>
        Friend Shared ReadOnly Property SP7() As String
            Get
                Return ResourceManager.GetString("SP7", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''Wyszukuje zlokalizowany ciąg podobny do ciągu The Sims™ 2 IKEA® urządza dom Akcesoria.
        '''</summary>
        Friend Shared ReadOnly Property SP8() As String
            Get
                Return ResourceManager.GetString("SP8", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''Wyszukuje zlokalizowany ciąg podobny do ciągu Ekran powitalny:.
        '''</summary>
        Friend Shared ReadOnly Property Splash() As String
            Get
                Return ResourceManager.GetString("Splash", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''Wyszukuje zlokalizowany ciąg podobny do ciągu Program uruchamiający The Sims™ 2.
        '''</summary>
        Friend Shared ReadOnly Property Title() As String
            Get
                Return ResourceManager.GetString("Title", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''Wyszukuje zlokalizowany ciąg podobny do ciągu Tak.
        '''</summary>
        Friend Shared ReadOnly Property Yes() As String
            Get
                Return ResourceManager.GetString("Yes", resourceCulture)
            End Get
        End Property
    End Class
End Namespace
